// kitsune-fe/src/components/Footer.vue
<template>
  <footer>
    <div v-if="instanceData" class="footer">
      <span>Kitsune v{{ instanceData.instance.version }}</span>
      <a target="_blank" href="https://github.com/kitsune-soc/kitsune"
        >Source code</a
      >
    </div>
  </footer>
</template>

<script setup lang="ts">
  import { useInstanceInfo } from '../graphql/instance-info';
  const instanceData = useInstanceInfo();
</script>

<style scoped lang="scss">
  @use '../styles/colours' as *;

  .footer {
    display: flex;
    justify-content: center;
    align-items: flex-end;
    padding: 10px 0;
    gap: 25px;
    margin-bottom: 25px;
  }
</style>

// kitsune-fe/src/lib/components/Footer.svelte
<script lang="ts">
	import Hangaku from '$assets/Hangaku.svelte';

	let { backendVersion, frontendVersion }: { backendVersion: string; frontendVersion: string } =
		$props();
</script>

<footer
	class="flex w-full place-content-between place-items-end text-sm max-lg:mb-5 max-lg:text-center lg:fixed lg:bottom-3 lg:left-3"
>
	<div>
		<p>
			Backend version: {backendVersion}
			<br />Frontend version: {frontendVersion}
		</p>

		<span>
			Powered by
			<a target="_blank" href="https://github.com/kitsune-soc/kitsune">Kitsune</a>
		</span>
	</div>

	<Hangaku class="w-64 -scale-x-100" />
</footer>
